version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src/:/app
  
  mongodb: 
    image: mongo:latest
    container_name: "mongodb_planning"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27019:27019